"use client";

// lib/supabase/client.ts

import {
  createBrowserClient,
} from "@supabase/ssr";
import type {
  AuthError,
  Session,
  SupabaseClient,
  User,
} from "@supabase/supabase-js";

import type {
  Database,
  ProfileRow,
} from "@/lib/supabase/types";

/*
|--------------------------------------------------------------------------
| Browser Supabase client + auth helpers
|--------------------------------------------------------------------------
|
| Everything here is resilient to Supabase not being configured yet. The
| factory returns null instead of throwing when the env vars are absent, so
| `next build` succeeds on a machine with no .env.local and the app quietly
| falls back to the local mock data in lib/data/.
|
| Four sign-in methods are supported:
|   1. Email    + password
|   2. Username + password  (mapped to a synthetic email, see below)
|   3. Facebook OAuth
|   4. Phone    + password
|
*/

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL;

const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

/*
 * Domain used to synthesise an email address for username-only accounts.
 *
 * Supabase Auth has no native username login: every account needs an email
 * or a phone. Rather than storing real emails and looking them up by
 * username at sign-in time (which would expose an enumeration endpoint -
 * anyone could probe which usernames exist and resolve them to a real
 * mailbox), a username deterministically maps to an address here and at
 * login the same address is rebuilt locally. No lookup, nothing leaked.
 *
 * Trade-off, documented deliberately: these addresses cannot receive mail,
 * so the standard "reset password by email" flow does not work for
 * username-only accounts until the user attaches a real address. See
 * linkEmailToAccount() at the bottom of this file.
 */
export const USERNAME_EMAIL_DOMAIN =
  "users.bazyanhub.app";

export function isSupabaseConfigured(): boolean {
  return Boolean(
    SUPABASE_URL && SUPABASE_ANON_KEY
  );
}

let browserClient:
  | SupabaseClient<Database>
  | null = null;

/*
 * Returns a memoised browser client, or null when credentials are missing.
 *
 * Callers MUST handle null. That is the whole point: it is what keeps the
 * app running before a Supabase project exists.
 */
export function getSupabaseClient():
  | SupabaseClient<Database>
  | null {
  if (!isSupabaseConfigured()) {
    return null;
  }

  if (!browserClient) {
    browserClient = createBrowserClient<Database>(
      SUPABASE_URL as string,
      SUPABASE_ANON_KEY as string
    );
  }

  return browserClient;
}

/*
|--------------------------------------------------------------------------
| Result shape
|--------------------------------------------------------------------------
|
| Every helper resolves rather than throws, so callers can render an error
| message without a try/catch around each call.
|
*/

export type AuthResult = {
  user: User | null;
  session: Session | null;
  error: AuthError | Error | null;
};

const NOT_CONFIGURED_ERROR = new Error(
  "Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL and " +
    "NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local (see .env.example)."
);

function notConfigured(): AuthResult {
  return {
    user: null,
    session: null,
    error: NOT_CONFIGURED_ERROR,
  };
}

/*
|--------------------------------------------------------------------------
| Username helpers
|--------------------------------------------------------------------------
*/

/*
 * Mirrors the CHECK constraint on profiles.username in supabase-schema.sql.
 * Validated client-side too so the user gets an immediate message instead of
 * a raw Postgres constraint violation.
 */
const USERNAME_PATTERN = /^[a-z0-9_]{3,30}$/;

export function normalizeUsername(
  username: string
): string {
  return username.trim().toLowerCase();
}

export function isValidUsername(
  username: string
): boolean {
  return USERNAME_PATTERN.test(
    normalizeUsername(username)
  );
}

export function usernameToEmail(
  username: string
): string {
  return `${normalizeUsername(username)}@${USERNAME_EMAIL_DOMAIN}`;
}

/*
 * True when an address was generated by usernameToEmail() rather than
 * supplied by the user. Useful for prompting "add a real email so you can
 * recover your account".
 */
export function isSyntheticEmail(
  email: string | null | undefined
): boolean {
  return Boolean(
    email?.toLowerCase().endsWith(
      `@${USERNAME_EMAIL_DOMAIN}`
    )
  );
}

/*
|--------------------------------------------------------------------------
| 1. Email + password
|--------------------------------------------------------------------------
*/

export async function signUpWithEmail(
  email: string,
  password: string,
  options?: {
    fullName?: string;
    username?: string;
  }
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const { data, error } =
    await supabase.auth.signUp({
      email: email.trim(),
      password,
      options: {
        data: {
          auth_method: "email",
          full_name: options?.fullName ?? null,
          username: options?.username
            ? normalizeUsername(options.username)
            : null,
        },
      },
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

export async function signInWithEmail(
  email: string,
  password: string
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const { data, error } =
    await supabase.auth.signInWithPassword({
      email: email.trim(),
      password,
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

/*
|--------------------------------------------------------------------------
| 2. Username + password
|--------------------------------------------------------------------------
|
| NOTE: "Confirm email" must be turned OFF in the Supabase dashboard
| (Authentication -> Providers -> Email) for this to work, because the
| synthetic addresses cannot receive a confirmation link.
|
*/

export async function signUpWithUsername(
  username: string,
  password: string,
  options?: { fullName?: string }
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const normalized = normalizeUsername(username);

  if (!isValidUsername(normalized)) {
    return {
      user: null,
      session: null,
      error: new Error(
        "Username must be 3-30 characters: lowercase letters, numbers and underscores only."
      ),
    };
  }

  const { data, error } =
    await supabase.auth.signUp({
      email: usernameToEmail(normalized),
      password,
      options: {
        /*
         * handle_new_user() lifts `username` out of raw_user_meta_data and
         * into the unique profiles.username column. A duplicate username
         * therefore surfaces as a unique-violation from that trigger.
         */
        data: {
          auth_method: "username",
          username: normalized,
          full_name: options?.fullName ?? null,
        },
      },
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

export async function signInWithUsername(
  username: string,
  password: string
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const normalized = normalizeUsername(username);

  if (!isValidUsername(normalized)) {
    return {
      user: null,
      session: null,
      error: new Error("Invalid username."),
    };
  }

  const { data, error } =
    await supabase.auth.signInWithPassword({
      email: usernameToEmail(normalized),
      password,
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

/*
 * Cheap pre-flight check for a signup form. Returns false when the username
 * is already taken.
 *
 * Note this reads public.profiles, which is NOT publicly readable under the
 * RLS policies in supabase-schema.sql - so for an anonymous visitor this
 * always reports "available" and the real conflict surfaces on submit. That
 * is the intended trade-off: no anonymous username enumeration. If you want
 * a live "username taken" indicator, add a SECURITY DEFINER RPC that returns
 * only a boolean (never the matching row) and call that instead.
 */
export async function isUsernameAvailable(
  username: string
): Promise<boolean> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return true;
  }

  const { data, error } = await supabase
    .from("profiles")
    .select("id")
    .eq("username", normalizeUsername(username))
    .maybeSingle();

  if (error) {
    return true;
  }

  return data === null;
}

/*
|--------------------------------------------------------------------------
| 3. Facebook OAuth
|--------------------------------------------------------------------------
|
| Requires a Facebook App ID + Secret in the Supabase dashboard
| (Authentication -> Providers -> Facebook).
|
| This redirects the browser, so on success it does not return - the promise
| only resolves meaningfully on failure.
|
*/

export async function signInWithFacebook(
  redirectTo?: string
): Promise<{ error: AuthError | Error | null }> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return { error: NOT_CONFIGURED_ERROR };
  }

  const { error } =
    await supabase.auth.signInWithOAuth({
      provider: "facebook",
      options: {
        redirectTo:
          redirectTo ??
          (typeof window !== "undefined"
            ? `${window.location.origin}/`
            : undefined),
        scopes: "email,public_profile",
      },
    });

  return { error };
}

/*
|--------------------------------------------------------------------------
| 4. Phone + password
|--------------------------------------------------------------------------
|
| INERT UNTIL CONFIGURED. Supabase needs an SMS provider (Twilio,
| MessageBird, Vonage or Textlocal) wired up under
| Authentication -> Providers -> Phone before any of this works. Until then
| these calls return a provider error from Supabase, not a crash.
|
| Phone numbers must be in E.164 format, e.g. +9647500000000.
|
*/

const E164_PATTERN = /^\+[1-9]\d{6,14}$/;

export function isValidPhone(
  phone: string
): boolean {
  return E164_PATTERN.test(phone.trim());
}

export async function signUpWithPhone(
  phone: string,
  password: string,
  options?: { fullName?: string }
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const trimmed = phone.trim();

  if (!isValidPhone(trimmed)) {
    return {
      user: null,
      session: null,
      error: new Error(
        "Phone number must be in international format, e.g. +9647500000000."
      ),
    };
  }

  const { data, error } =
    await supabase.auth.signUp({
      phone: trimmed,
      password,
      options: {
        data: {
          auth_method: "phone",
          full_name: options?.fullName ?? null,
        },
      },
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

export async function signInWithPhone(
  phone: string,
  password: string
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const { data, error } =
    await supabase.auth.signInWithPassword({
      phone: phone.trim(),
      password,
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

/*
 * Confirms a phone signup with the 6-digit code from the SMS. Only needed
 * when "Confirm phone" is enabled in the dashboard.
 */
export async function verifyPhoneOtp(
  phone: string,
  token: string
): Promise<AuthResult> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return notConfigured();
  }

  const { data, error } =
    await supabase.auth.verifyOtp({
      phone: phone.trim(),
      token: token.trim(),
      type: "sms",
    });

  return {
    user: data.user,
    session: data.session,
    error,
  };
}

/*
|--------------------------------------------------------------------------
| Session & profile
|--------------------------------------------------------------------------
*/

export async function signOut(): Promise<{
  error: AuthError | Error | null;
}> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return { error: NOT_CONFIGURED_ERROR };
  }

  const { error } =
    await supabase.auth.signOut();

  return { error };
}

export async function getSession(): Promise<Session | null> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return null;
  }

  const { data } =
    await supabase.auth.getSession();

  return data.session;
}

/*
 * Prefer this over getSession().user when the answer matters for anything
 * security-adjacent: getUser() revalidates the token against the server,
 * whereas getSession() trusts whatever is in local storage.
 */
export async function getCurrentUser(): Promise<User | null> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return null;
  }

  const { data } =
    await supabase.auth.getUser();

  return data.user;
}

export async function getCurrentProfile(): Promise<ProfileRow | null> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return null;
  }

  const user = await getCurrentUser();

  if (!user) {
    return null;
  }

  const { data, error } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", user.id)
    .maybeSingle();

  if (error) {
    return null;
  }

  return data;
}

/*
 * Attaches a real email address to an account that signed up with a username
 * (and therefore has a synthetic, unreachable address). This is what makes
 * email-based password recovery possible for those accounts.
 *
 * Supabase sends a confirmation link to the NEW address; the change only
 * takes effect once that link is clicked.
 */
export async function linkEmailToAccount(
  email: string
): Promise<{ error: AuthError | Error | null }> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return { error: NOT_CONFIGURED_ERROR };
  }

  const { error } =
    await supabase.auth.updateUser({
      email: email.trim(),
    });

  return { error };
}

export async function sendPasswordReset(
  email: string,
  redirectTo?: string
): Promise<{ error: AuthError | Error | null }> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    return { error: NOT_CONFIGURED_ERROR };
  }

  if (isSyntheticEmail(email)) {
    return {
      error: new Error(
        "This account has no real email address. Sign in with your username " +
          "and password, then add an email to enable password recovery."
      ),
    };
  }

  const { error } =
    await supabase.auth.resetPasswordForEmail(
      email.trim(),
      {
        redirectTo:
          redirectTo ??
          (typeof window !== "undefined"
            ? `${window.location.origin}/`
            : undefined),
      }
    );

  return { error };
}
